apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWGlHM01LS05nWW93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMk1qVXhOVE0wTXpsYUZ3MHpOakEyTWpJeE5UTTVNemxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNsbVRlVGs1Z1dpcmp0UXNDQ0QxNG1sUVlWb09aTVViVnZlUE03SmxhUmcrSU8wRThNVDZ2aEl0S0oKVzQ0UzFleWJ4QVJQbGVmOEJDUUtseGdySjRkWVAvTmt4a2NFZGV6OGljSWJiOUZpN3l5SGwyeVdFc1lQTHQ1NQpNZmcxRHB0dlpBZG9vbWwxQ1kyMEFBUTd2cUhZdTRyQjhBR0wreGVIcWx0KzFrK2FhOFAxRFRoYSt5azAzRjRHCmNKdWlsdHI3NDJtTTRpVGNtSWEyVmMzSEN0dXBCZ1orNmZZM29QM2I4V3l3WjJaSVhpTzlIL0lJQWhKSWhpZVgKeDg4eUhhTGVuajlNN1EvTDhRczRzZjk0ai83eEhhYUJPNDh4anNZRG1XdXdJb0RGemhKcG1rTzdDYUUzZzFIZgpNWDIrOUw4d0wvbTBCK3dmTmNXMWN4azc4UGNGQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTOUJIbVpoSTlDNzRVakZBZWtnMU4yTlJXV2pUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUtUUENPODFCbApJM0JlRWxyOGFLVG9jMzVsTThBQ29TeThpdkFlVTF6V3A5TW9PT0NVZWc4SFZNOUgwK21XS0ZZN1ZobWZQbkgxCm9XT3FxTkdPSmN3Q0hRL3NZZW8xVmNsNjdxUG1sTENNS3FGbVl1TmUrY2R4THZuL2hzYUVmK0J4WFJPakVwNG0KeCtpRUUwUGZaOUk4WDloMWxhZXBUUk1JWGE0TnptNXd4eDVyUlduM0NQV0MxUGM1Vll2aXlSd0lxLzY0enpndgpLQm1aL3BIMGNBWTlLYTEwSFBoZVZPWTFpNUhrS2dwZk1sQTk4M1hXWFR1ZHNVbkNZTG02R0ZCQi83b1AwL1VwClI3SFU4M2JlalZmdm5HYTlOZThIWWZnME9Tc2d5bjB2ZUpUZWpMY0YrZVlRdzZ1NGpsZlpRa0JoQ25FV2lIcG4Ka1dZaCtlUXdSUFFHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://172.18.0.2:6443
  name: re
contexts:
- context:
    cluster: re
    user: system:node:re-control-plane
  name: system:node:re-control-plane@re
current-context: system:node:re-control-plane@re
kind: Config
users:
- name: system:node:re-control-plane
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem
